### PR TITLE
#59 Service Wrapper Component

### PR DESCRIPTION
**Pull request by alexfox361**
This pull request aims to resolve issue #59. To do this I have added the Service Wrapper Component.

## New Features

- Service Wrapper Component
  - This component allows for text field, button, and image to be added. 
- Service Wrapper Options Component
  - Allows modification of all fields. 

### Service Wrapper (Light Mode)

image

### Service Wrapper (Dark Mode) 

image

### ServiceWrapper.jsx

- Added the Service Wrapper component and styled it

### ServiceWrapperOptions.jsx

- Added the Service Wrapper options to be modified by the user

### ServiceWrapperPreview.png

- Added preview for the components tab

### registeredComponents.js

- Added the component and its default fields to the components array.

### CODE REVIEW

**Review by CrystaS15 — COMMENTED** [review]
I tried running the code on my end, but I could not test out the components because they would not appear on the Portfolio website UI kit. it seems you added the files to the `registeredComponents.js` file, but it does not show on my end. On my end, I could not branch into the files to test them out. I'm not sure if it's just me, but I can't seem to get this component to work either.

**Comment by Lettuce05** [comment]
[Open in Codeflow](https://pr.new/github.com/cs472-team6/cs472-team6/pull/77)

**Review by CrystaS15 — APPROVED** [review]
I saw that the functionalities of the options components ran properly, and I did not see any bugs or issues. I can see that the texts, gradients, and button all do as their function should suggest.

**Review by CruzG-Dylan — APPROVED** [review]
Everything seems to be functioning as intended. No major bugs or issues when modifying the options.

**Pull request merged**
