### PR TITLE
Update responsiveness to FourZeroFour component

### PR DESCRIPTION
**Pull request by Thindatuo**
add responsiveness to screen size of a phone to 404 component.
So that it looks like this on large screens:
image
and like this on small screens:
image

file changed:
FourZeroFour.jsx

### CODE REVIEW

**Review by ebacolod — CHANGES_REQUESTED** [review]
The 404 component flex items are horizontal at small screen sizes.

image

In your code, you don't need to include the `sm:` prefix, so the only thing you need to do is remove them. Here's some information about how tailwind does responsive design: https://tailwindcss.com/docs/responsive-design#targeting-mobile-screens

**Comment by Thindatuo** [comment]
Hi, Ethan, thank you for the review and thoughts on how to make change! I've removed all the "sm" prefix in the latest commit, it would transfer to horizontal view when the screen size is of "sm", but it looks a little out of order on the way from "md" to "sm", I wonder if that's acceptable.

**Comment by ebacolod** [comment]
> Hi, Ethan, thank you for the review and thoughts on how to make change! I've removed all the "sm" prefix in the latest commit, it would transfer to horizontal view when the screen size is of "sm", but it looks a little out of order on the way from "md" to "sm", I wonder if that's acceptable.

Can you share screenshots so I can get a better understanding? (Two screenshots from before and after the transition)

**Comment by Thindatuo** [comment]
> > Hi, Ethan, thank you for the review and thoughts on how to make change! I've removed all the "sm" prefix in the latest commit, it would transfer to horizontal view when the screen size is of "sm", but it looks a little out of order on the way from "md" to "sm", I wonder if that's acceptable.
> 
> Can you share screenshots so I can get a better understanding? (Two screenshots from before and after the transition)

So this is like the md size looking: 
image
this is for sm size, which is the default:
image
and this is like in the middle: 
image

**Comment by ebacolod** [comment]
iirc, I believe we look at the component when it's in Dev View because that's what the portfolio will look like when it gets exported. And with the current changes, your component looks good in Dev View. I think we kinda talked about this issue with the sidebar open. I forgot what the solution though. We can discuss it more in today's meeting and see if it needs to be addressed.

**Comment by Thindatuo** [comment]
> 

Thank you! My bad to miss that one.  I've removed that in the latest commit.

**Review by ebacolod — APPROVED** [review]
Thanks for making all these changes. The responsiveness works nicely. I approve!

**Review by WuliuQ — APPROVED** [review]
I run the code, and it works like the change you described, so I approve these change.

**Pull request merged**
