### PR TITLE
Add Info Modal

### PR DESCRIPTION
**Pull request by alexfox361**
This Pull Request adds an Information Modal to explain how to use key features of the site. 

The information is accessed by selecting the "i" button at the top left of the screen. This will then open a modal that gives information on core functionality such as: Adding Components, Customizing Components, Customizing the Website Details, Exporting the Website, and Exporting the Save Data. 

## PREVIEW
image

## CODE CHANGES

src/App.jsx
- Added the modal to the page.

src/components/InfoModal/InfoModal.jsx: 
- Added the modal design and details. 
- Used state to determine when shown. 

src/components/Navbar/Navbar.jsx:
- Added the Info Button to the page.
- Apply state change when selected. 

src/state.js: 
- Added new state functions to determine when the info modal is shown.

### CODE REVIEW

**Review by Lettuce05 — CHANGES_REQUESTED** [review]
I think that the "i" button and modal looks good, however the modal is cut off on my screen (I cannot view all of the contents of the modal or even see the entire shape of the modal). This is happening because you are not accounting for screens with smaller heights (I am on a 13in macbook). This should be an easy fix, all you should have to do is make the modal smaller. Another approach would be to make the container of the modal scrollable.

Screen Shot 2023-04-29 at 9 33 23 PM


I also see that their is merge conflicts with Navbar.jsx so those need fixed as well.

**Comment by alexfox361** [comment]
Hey @Lettuce05, I fixed the height issue so that only 3/5 of the page is taken up by the modal. I tested this on different screen sized and it seemed to work well. 

I also fixed the merge conflict.

Let me know what you think. Thank you!

**Review by Lettuce05 — APPROVED** [review]
With the updated changes the modal works at all screen sizes and all of the content is able to be seen.

image

The implementation of the code is very simple and will be easy to understand for another developer.

All tests pass and project builds successfully.

The only comment I would add is that there was no test added for this component. This would be nice in order to increase code coverage.

**Review by CrystaS15 — APPROVED** [review]
The component is visible, works well, and the information pops up properly. The visibility is not an issue and there is important information regarding how to use the key features on the website. The screen size adapts properly too. 

All the tests do pass as well. I do not see any tests for this component or issue, but the everything works accordingly.

**Pull request merged**
