### PR TITLE
Add CtaSection Component

### PR DESCRIPTION
**Pull request by WuliuQ**
This pull request aims to resolve issue https://github.com/cs472-team6/cs472-team6/issues/52. In this pull request I create the CtaSection Component.

### **New Features**

- CtaSection Component
   This new component allows user to add their link and slogan.

### **Screenshots of New Feature**
CtaSection Component（Dark）
darkcta

CtaSection Component（Light）
lightcta

### Code Changes
**CtaSection.jsx**
Added the CtaSection component (this is the function that is used to render the component in the PreviewPanel)

**CtaSectionOptions.jsx**
Added the CtaSectionOptions component (this is the function that is used to render the component in the ComponentOptionsTab)

**CtaSectionPreview.png**
Image used to display the preview of the CtaSection component in the ComponentsListTab

**vector.svg**
Image used to show the arrow after the link

**registeredComponents.js**
Added CtaSection component to the array

### CODE REVIEW

**Comment by Lettuce05** [comment]
[Open in Codeflow](https://pr.new/github.com/cs472-team6/cs472-team6/pull/71)

**Review by CrystaS15 — APPROVED** [review]
I ran the code and saw that it implements the CtaSection Component properly. The link worked well and I did not see any bugs or issues.

**Review by ZacheryEC001 — CHANGES_REQUESTED** [review]
I have reviewed the code request and everything works on my end. One thing that could be changed is the gradient on the text. In the utils.js folder, we have a list of gradients that the user can choose from to customize their portfolio. An example of an implementation of this can be found in the banner component. 
By using this list of gradients, we can expand user choice very easily without changing every component that uses a gradient.

**Review by ZacheryEC001 — APPROVED** [review]
Everything works on my end and the gradient selection has been implemented.

**Pull request merged**
