### PR TITLE
Add functionality to export user website

### PR DESCRIPTION
**Pull request by Lettuce05**
This pull request aims to resolve issue #135. This pull request adds all the required functionality to allow the user to save the portfolio data as well as output website files that they can upload to a hosting service.

### ExportModal

Clicking the export button in the top right of the main navbar will prompt the user with the following modal.

- Export Data button
  - Clicking this button will download a JSON file to the user that saves the current status of their website design. This file will be used with a future feature that will allow the user to import the file and continue from where they left off.

- Export Website button
  - Clicking this button will download a ZIP file that contains a `dist` directory that the user can use to host the website or upload to hosting service. These website files are already optimized for production.  

image

**Loading state of the modal after export button is pushed.**

image

### .gitignore

- Add entry for files.js
  - In order to generate the website files to be exported we are using a webcontainer. The webcontainer needs a copy of all of the component files as well as some base project files. However, it needs the copy of these files in a JavaScript Object. Rather than manually copy and pasting the contents of the necessary files the filesystem.js script was created to generate a files.js file that contains the object which will be used as the file system for the webcontainer. This autogenerated file is quite large and although necessary for development and production, it should not be added to the git repository.

### filesystem.js

- Added script that compiles all the necessary files for the filesystem of the webcontainer into a files.js file in the form of a JavaScript Object that can be imported.

### package-lock.json

- Added the necessary packages in order to use webcontainers and zip files so the exported website can be downloaded to the user.

### package.json

- Added the necessary packages in order to use webcontainers and zip files so the exported website can be downloaded to the user.
- Added the fs script that calls the filesystem.js script
- Modified the dev and build scripts to call the fs script before they are run

### src/App.jsx

- Added the ExportModal to the main page of the application

### src/components/SocialMedia/SocialMediaComponent.js

- Replaced all imgur files with images hosted by a companion repo
- Replaced all images that had broken links

### src/components/ExportModal/ExportModal.jsx

- Added the ExportModal component
  - handleExportData()
      - Formats the values from PageState into a string and downloads the resulting JSON file to the user
  -  containerExists()
      - Checks whether the web container has already been created (there is only allowed to be one instance of web container
  - handleExportWebsite()
      - Creates the web container if it has not already been created 
      - Mounts the file system from the files.js file into the web container
      - Writes the PageState values into a file in the web container that can be used to create the users website
      - Creates a customized index.html file that will be used for the users website and writes it into a file in the web container
      - Installs the dependencies for the users website
      - Builds the users website into production ready website files
      - Extracts the generated build files and creates a zip folder that is then downloaded to the user
  - Utility functions for working with the filesystem of the web container and running commands within the container    
      - zipFolder()
      - readContainerFile()
      - readContainerDir()
      - installDependencies()
      - buildWebsite()

### src/components/Navbar/Navbar.jsx

- Added functionality to the export button to prompt the export modal

### src/models/PageOptions.js

- Corrected the default language options to be a correct html ISO language option

### src/state.js

- Added global state functionality to handle the state of the ExportModal
  - Handle displaying the modal
  - Handle loading status of the modal

### src/utils/registeredComponents.js

- Removed duplicate entry of the Stats Section component

### src/utils/utils.js

- toJSON()
  - Utility function that allows complex JavaScript Objects to be converted to string
-  createIndexHTML()
  - Utility function that takes in the pageOptions object and creates a customized index.html file for the web container in order to reflect the users desired settings for the exported website

### vite.config.js

- Added the necessary configuration settings to allow web containers to work
  - Web containers require the website to be cross-origin isolated

### webcontainer/vite.config.js

- Customized files required to run a react application inside the web container which will contain the functionality for the users generated website.
- These files mimic a simplified version of the main application (specifically the logic of the preview panel)

### CODE REVIEW

**Review by CrystaS15 — APPROVED** [review]
I noticed that the variable names are brief and descriptive, I can tell what the variables are used for. I also noticed that function parameters do have default values where it is appropriate. There is enough documentation to understand what the files and functions do. I checked out this PR and the export data button and export website buttons properly download a JSON file and ZIP file that contains the files specified.

**Review by CrystaS15 — CHANGES_REQUESTED** [review]
Even though I did notice that the proper files were downloaded, I'm not sure how to use the files to upload to the hosting site or host the site.

**Comment by Lettuce05** [comment]
@CrystaS15 I appreciate your thought however this PR only has to do with the export functionality. If you want you can open a new issue to add documentation. Keep in mind that the purpose of the application is so that users aren't locked into a hosting vender. There are many ways to host a website so we cannot put specific instructions for all ways/vendors. This would be a good issue to go along with the README issue/update that we have to do.

**Review by CrystaS15 — APPROVED** [review]
I see that now, I will approve the issue.

**Review by alexfox361 — APPROVED** [review]
Hey @Lettuce05 this PR works great. I was able to export the website and it downloaded a .zip file containing all the necessary files.  The JSON file works well and should be a nice feature when added in the future. 

Additionally, the tests work well. Code coverage is improved nicely from this ticket. 

I'm going to open up a new issue to add descriptions for each of these buttons, because I think that it will help the user understand what to do once the button is pushed. 

Nice job!

**Pull request merged**
