### PR TITLE
Added AboutHeadImages and AboutHeadSection Components

### PR DESCRIPTION
**Pull request by CrystaS15**
This pull request aims to resolve issues #48 and #51. In this pull request I have created the About section of the application and all requirements to obtain desired functionality.

# New Features #
1.  AboutHeadSection Component
2.  AboutHeadImages Component

# Screenshots of New Features #
All of the screenshots portray the new AboutHeadSection and AboutHeadImages.

#### Dark Mode ####
image

#### Light Mode ####
image

#### Dark Mode ####
image

#### Light Mode ####
image

# Code Changes #
1. AboutHeadImages.jsx
    - Added the AboutHeadImage component.
2. AboutHeadImagesOptions.jsx
    - Added the AboutHeadImage options component.
3. AboutHeadImagesPreview.png
    - Image used the display the preview of the AboutHeadImages component.
4. AboutHeadSection.jsx
    - Added the AboutHeadSection component.
5. AboutHeadSectionOptions.jsx
    - Added the AboutHeadSection options component.
6. AboutHeadSectionPreview.png
    - Image used the display the preview of the AboutHeadSection component.
7. registeredComponents.js
    - This is where all of the components that the user will be able to add to their website will be registered.
    - This array includes the new features of AboutHeadSection and AboutHeadImages components which will be used to render the appropriate component for each panel/feature of the application.

### CODE REVIEW

**Review by CruzG-Dylan — CHANGES_REQUESTED** [review]
The AboutHeadSection component seems to work as intended, but the default images for the AboutHeadImages component (**_at least on my end_**) seems to be only [object Object] so it doesn't display anything, but I think you wanted the default to be the .svg files. If the .svg files weren't supposed to be the default there is no need to import the images in the registeredComponents.js file.

This is what I see using StackBlitz CodeFlow
image

**Comment by CrystaS15** [comment]
> The AboutHeadSection component seems to work as intended, but the default images for the AboutHeadImages component (**_at least on my end_**) seems to be only [object Object] so it doesn't display anything, but I think you wanted the default to be the .svg files. If the .svg files weren't supposed to be the default there is no need to import the images in the registeredComponents.js file.
> 
> This is what I see using StackBlitz CodeFlow image

I made it so that the images for the AboutHeadImages component shows as image links.

**Review by CruzG-Dylan — APPROVED** [review]

**Review by ZacheryEC001 — CHANGES_REQUESTED** [review]
Looking good, but when I initialize the AboutHeadImages section, none of the images render properly. When I change the url to the locally stored images (in /src/components/AboutHeadImages), they show up.

Additionally, did you mean to implement the social media buttons on the AboutHeadSection for this PR? If you're strapped for time, I'd recommend creating a new issue and addressing that implementation in another PR. Let me know and I'll approve the merge after.

**Review by ZacheryEC001 — APPROVED** [review]
The image issue from my last review was confirmed to be on my end. I would suggest making an issue for the social media buttons and address them in another PR.

**Pull request merged**
