### PR TITLE
Add Blog page content section component and Update CtaSection component

### PR DESCRIPTION
**Pull request by WuliuQ**
This pull request aims to resolve issue https://github.com/cs472-team6/cs472-team6/issues/69. In this pull request I create the CtaSection Component.

### **New Features**

- Blog page content section Component
  This new component allows user to add their paragraph, image and header.

### **Screenshots of New Feature**

- Blog page content section Component (Dark)
blogdark

- Blog page content section Component (Light)
bloglight

### **Code Changes**
**BlogPage.jsx**
Added the BlogPage component (this is the function that is used to render the component in the PreviewPanel)

**BlogPageOptions.jsx**
Added the BlogPage component (this is the function that is used to render the component in the ComponentOptionsTab)

**BlogPagePreview.png**
Image used to display the preview of the BlogPage component in the ComponentsListTab

**registeredComponents.js**
Added BlogPage component to the array

**BlogPageComponent.js**
Use as a variable in registeredComponents.js

**CtaSection.jsx**
Let the size of word change by the windows size

**CtaSectionComponent.js**
Use as a variable in registeredComponents.js

### CODE REVIEW

**Comment by alexfox361** [comment]
Hey @WuliuQ! Nice work so far, but there is a few issues with this PR so far. Firstly I think that this component should just include one image. Next, there is a custom font that should be used for styling, I believe you can access this by adding 
```text-primary``` to the text areas. Lastly, this component does not have any logic for different screen sizes. When the screen changes sizes (sm, md, lg) the component should change in order to match the design on Figma. 

Here's a link that explains Tailwind's built in utility for this: 
https://tailwindcss.com/docs/responsive-design

Let me know if you have any questions.

**Review by alexfox361 — CHANGES_REQUESTED** [review]
Hey @WuliuQ! Nice work so far, but there is a few issues with this PR so far. Firstly I think that this component should just include one image. Next, there is a custom font that should be used for styling, I believe you can access this by adding 
```font-main``` to the text areas. Lastly, this component does not have any logic for different screen sizes. When the screen changes sizes (sm, md, lg) the component should change in order to match the design on Figma. 

Here's a link that explains Tailwind's built in utility for this: 
https://tailwindcss.com/docs/responsive-design

Let me know if you have any questions.

**Review by CrystaS15 — APPROVED** [review]
I can see that the `BlogPageComponent.js` file cleans up the `registeredComponents.js` file nicely. I do not see any issues with the code, the `BlogPageOptions.jsx` file also looks straightforward. 

I ran the code, and it runs on the Portfolio builder in light and dark modes well. The inputs for the Overview, Paragraph, and Image URL also work for me.

**Comment by WuliuQ** [comment]
For the image, I think it is ok for the three sizes that shows on figma.

**Comment by alexfox361** [comment]
Hey @WuliuQ, this looks much better. There's still a couple of issues. It looks like you applied the font to the options text, and not the text on the page. 

Other than that, it looks like the font could be the wrong size on smaller screens. I think if you are able to lower it once it gets to phone size that would be good. I think it could also use a width for the text box. Right now the words go off the page if the paragraph is too long.

**Review by alexfox361 — APPROVED** [review]
Hey @WuliuQ, Nice work with the changes. I think that this should work for now. Eventually I think we should change the preview picture and clarify some of the text a little bit better, but for now I think it works great. 

Nice work!

**Pull request merged**
