### PR TITLE
Add CtaSection2 Component

### PR DESCRIPTION
**Pull request by WuliuQ**
This pull request aims to resolve issue https://github.com/cs472-team6/cs472-team6/issues/118. In this pull request I create the CtaSection2 Component and the test for CtaSection2 Component.

### **New Features**

- CtaSection2 Component
  This new component allows user to add their slogan and link.

### **Screenshots of New Feature**

- CtaSection2 Component (Dark)
dark

- CtaSection2 Component (Light)
light

### **Code Changes**
**CtaSection2.jsx**

- Added the CtaSection2 component (this is the function that is used to render the component in the PreviewPanel)

**CtaSection2.jsx**

- Added the CtaSection2 component (this is the function that is used to render the component in the ComponentOptionsTab)

**CtaSection2Preview.png**

- Image used to display the preview of the CtaSection2 component in the ComponentsListTab

**registeredComponents.js**

- Added CtaSection2 component to the array

**CtaSection2Component.js**

- Use as a variable in registeredComponents.js

**CtaSection2UML.png**

- UML showing the CtaSection2 use case

**CtaSection2.test.jsx**

- Added tests in order to obtain code coverage of the CtaSection2 component and its corresponding files and functionality.
 The screenshot shows the tests provide 100% code coverage for the CtaSection2 component.
coverage

### CODE REVIEW

**Review by arroya2 — APPROVED** [review]
The component does work as intended and all the options to change the color, URL button link, and text also do work as intended. The only warning I got that doesn't seem to be an issue (and might be able to work without it being fixed because it worked fine on my end) is that in the CtaSection2.jsx file the "class" needs to be changed to "className" 

Also all three tests passed on.my end as well for this component

**Review by Lettuce05 — CHANGES_REQUESTED** [review]
Great Work! Everything works as expected. The project builds sucessfully, the component is responsive, and I am able to update the component properly. My only suggestion is that when getting to the breakpoint for the smaller screen size there is a lot of extra room on both sides of the component. I have included screenshots of the current component vs the figma design. My suggestion would be to make the width responsive like 80% or 90% at the smaller screen size.

Current Component

image

Figma design

image

I was able to confirm the code coverage provided by the included tests and verified that all the test pass properly.

image

**Review by CrystaS15 — APPROVED** [review]
The component works as intended on my end. The light and dark modes are properly implemented. All the text inputs and the links work as intended as well and I can change the gradient as I wish. 

I can also see here that all the tests passed.
image

The code coverage also shows up complete on my end as well.
image

I do not see any issues with the screen sizes. I am not sure if there are any other bugs, but I do not see any.

**Review by Lettuce05 — APPROVED** [review]
Great Work! There is still quite a large gap around the component at smaller sizes however I think that it is fine to leave it like this.

There is full coverage for the component and all the test pass.

image

image

**Pull request merged**
